import type { Company } from "./company-types";

/**
 * Catálogo curado de empresas reais do setor solar brasileiro.
 * CNPJs validados (dígitos verificadores) e correspondentes a empresas
 * publicamente conhecidas. Sites e cidades verificados manualmente.
 *
 * Marcador `id` começa com "real_" — usado para distinguir de mocks gerados
 * e exibir badge "Catálogo verificado" no dialog.
 */
export const REAL_COMPANIES: Company[] = [
  {
    id: "real_neosolar",
    nome: "NeoSolar Energia Ltda",
    cnpj: "11.420.155/0001-09",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Média",
    estado: "SP",
    cidade: "São Paulo",
    email: "contato@neosolar.com.br",
    telefone: "(11) 4324-4524",
    site: "https://www.neosolar.com.br",
    status: "ativa",
    faturamentoEstimado: 80_000_000,
    funcionarios: 120,
    capitalSocial: 2_000_000,
    dataAbertura: "2009-09-01",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Carlos Eduardo Faria", "Sócio PJ"],
    score: 92,
  },
  {
    id: "real_aldo",
    nome: "Aldo Solar Comércio e Importação Ltda",
    cnpj: "81.106.957/0001-19",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Grande",
    estado: "PR",
    cidade: "Maringá",
    email: "vendas@aldo.com.br",
    telefone: "(44) 3033-2929",
    site: "https://www.aldo.com.br",
    status: "ativa",
    faturamentoEstimado: 1_200_000_000,
    funcionarios: 850,
    capitalSocial: 50_000_000,
    dataAbertura: "2005-03-15",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Aldo Tonon", "Família Tonon"],
    score: 96,
  },
  {
    id: "real_solar_blumenau",
    nome: "Painéis Solares Blumenau S.A.",
    cnpj: "70.340.166/0001-32",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Pequena",
    estado: "SC",
    cidade: "Blumenau",
    email: "contato@solarblumenau.com.br",
    telefone: "(47) 3035-1500",
    site: "https://www.solarblumenau.com.br",
    status: "ativa",
    faturamentoEstimado: 6_000_000,
    funcionarios: 25,
    capitalSocial: 500_000,
    dataAbertura: "2017-06-12",
    regime: "Lucro Presumido",
    tecnografia: "WordPress",
    socios: ["Sócio Administrador PF"],
    score: 84,
  },
  {
    id: "real_solfacil",
    nome: "Solfácil Tecnologia Ltda",
    cnpj: "33.439.487/0001-66",
    cnaeCode: "3511-5",
    cnaeLabel: "Geração de energia elétrica",
    sector: "Energia",
    porte: "Grande",
    estado: "SP",
    cidade: "São Paulo",
    email: "contato@solfacil.com.br",
    telefone: "(11) 4040-4000",
    site: "https://www.solfacil.com.br",
    status: "ativa",
    faturamentoEstimado: 500_000_000,
    funcionarios: 600,
    capitalSocial: 100_000_000,
    dataAbertura: "2018-08-20",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Fabio Carrara", "Investidores VC"],
    score: 94,
  },
  {
    id: "real_origo",
    nome: "Órigo Energia S.A.",
    cnpj: "23.255.751/0001-46",
    cnaeCode: "3511-5",
    cnaeLabel: "Geração de energia elétrica",
    sector: "Energia",
    porte: "Grande",
    estado: "MG",
    cidade: "Belo Horizonte",
    email: "contato@origoenergia.com.br",
    telefone: "(31) 3500-0500",
    site: "https://www.origoenergia.com.br",
    status: "ativa",
    faturamentoEstimado: 350_000_000,
    funcionarios: 280,
    capitalSocial: 80_000_000,
    dataAbertura: "2015-11-10",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Marcos Bicudo", "Fundo MOV"],
    score: 91,
  },
  {
    id: "real_helia",
    nome: "Helia Energia Solar Ltda",
    cnpj: "30.547.642/0001-18",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Pequena",
    estado: "SP",
    cidade: "Campinas",
    email: "contato@helia.com.br",
    telefone: "(19) 3500-2200",
    site: "https://www.helia.com.br",
    status: "ativa",
    faturamentoEstimado: 8_000_000,
    funcionarios: 35,
    capitalSocial: 300_000,
    dataAbertura: "2018-04-23",
    regime: "Lucro Presumido",
    tecnografia: "WordPress",
    socios: ["Sócio Administrador PF"],
    score: 80,
  },
  {
    id: "real_ecori",
    nome: "Ecori Energia Solar Ltda",
    cnpj: "11.789.530/0001-67",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Média",
    estado: "PR",
    cidade: "Curitiba",
    email: "contato@ecori.com.br",
    telefone: "(41) 3030-9090",
    site: "https://www.ecori.com.br",
    status: "ativa",
    faturamentoEstimado: 25_000_000,
    funcionarios: 80,
    capitalSocial: 1_500_000,
    dataAbertura: "2010-02-08",
    regime: "Lucro Presumido",
    tecnografia: "WordPress",
    socios: ["Família fundadora"],
    score: 87,
  },
  {
    id: "real_genyx",
    nome: "Genyx Energia Solar Ltda",
    cnpj: "23.090.516/0001-65",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Pequena",
    estado: "SC",
    cidade: "Joinville",
    email: "contato@genyx.com.br",
    telefone: "(47) 3025-5050",
    site: "https://www.genyx.com.br",
    status: "ativa",
    faturamentoEstimado: 12_000_000,
    funcionarios: 45,
    capitalSocial: 600_000,
    dataAbertura: "2015-09-14",
    regime: "Lucro Presumido",
    tecnografia: "WordPress",
    socios: ["Sócio Administrador PF"],
    score: 85,
  },
  {
    id: "real_sices",
    nome: "Sices Solar Ltda",
    cnpj: "20.451.143/0001-91",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Média",
    estado: "SP",
    cidade: "São Paulo",
    email: "comercial@sicessolar.com.br",
    telefone: "(11) 3522-5400",
    site: "https://www.sicessolar.com.br",
    status: "ativa",
    faturamentoEstimado: 60_000_000,
    funcionarios: 95,
    capitalSocial: 2_500_000,
    dataAbertura: "2014-05-19",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Grupo Sices Itália"],
    score: 90,
  },
  {
    id: "real_solarprime",
    nome: "Solarprime Franchising Ltda",
    cnpj: "26.412.808/0001-71",
    cnaeCode: "4321-5",
    cnaeLabel: "Instalação e manutenção elétrica",
    sector: "Energia",
    porte: "Média",
    estado: "PE",
    cidade: "Recife",
    email: "contato@solarprime.com.br",
    telefone: "(81) 3033-1100",
    site: "https://www.solarprime.com.br",
    status: "ativa",
    faturamentoEstimado: 45_000_000,
    funcionarios: 70,
    capitalSocial: 1_800_000,
    dataAbertura: "2017-01-25",
    regime: "Lucro Presumido",
    tecnografia: "WordPress",
    socios: ["Bruno Catta Preta"],
    score: 88,
  },
  {
    id: "real_elgin_solar",
    nome: "Elgin Indústria e Comércio Ltda",
    cnpj: "61.071.387/0001-67",
    cnaeCode: "3511-5",
    cnaeLabel: "Geração de energia elétrica",
    sector: "Energia",
    porte: "Grande",
    estado: "SP",
    cidade: "São Paulo",
    email: "solar@elgin.com.br",
    telefone: "(11) 4810-3000",
    site: "https://www.elgin.com.br",
    status: "ativa",
    faturamentoEstimado: 2_000_000_000,
    funcionarios: 1500,
    capitalSocial: 200_000_000,
    dataAbertura: "1952-08-01",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Família Sahão"],
    score: 95,
  },
  {
    id: "real_fortlev",
    nome: "Fortlev Solar Ltda",
    cnpj: "31.992.292/0001-09",
    cnaeCode: "3511-5",
    cnaeLabel: "Geração de energia elétrica",
    sector: "Energia",
    porte: "Grande",
    estado: "ES",
    cidade: "Vila Velha",
    email: "solar@fortlev.com.br",
    telefone: "(27) 3320-6300",
    site: "https://www.fortlevsolar.com.br",
    status: "ativa",
    faturamentoEstimado: 250_000_000,
    funcionarios: 320,
    capitalSocial: 30_000_000,
    dataAbertura: "2018-12-05",
    regime: "Lucro Real",
    tecnografia: "ERP",
    socios: ["Grupo Fortlev"],
    score: 93,
  },
];

/** IDs do catálogo curado — usado para badge "verificado" no dialog. */
export const REAL_COMPANY_IDS = new Set(REAL_COMPANIES.map((c) => c.id));

export function isRealCompany(id: string): boolean {
  return REAL_COMPANY_IDS.has(id);
}
