/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProspectingRouteImport } from './routes/prospecting'
import { Route as ModelosDeSitesRouteImport } from './routes/modelos-de-sites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IaVendasRouteImport } from './routes/ia-vendas'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as FollowupRouteImport } from './routes/followup'
import { Route as DueDiligenceRouteImport } from './routes/due-diligence'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BuscadorRouteImport } from './routes/buscador'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ModelosDeSitesIndexRouteImport } from './routes/modelos-de-sites.index'
import { Route as ServicosOfertasRouteImport } from './routes/servicos.ofertas'
import { Route as ServicosNovosRouteImport } from './routes/servicos.novos'
import { Route as ServicosIaRouteImport } from './routes/servicos.ia'
import { Route as ServicosDocumentacaoRouteImport } from './routes/servicos.documentacao'
import { Route as ServicosCombosRouteImport } from './routes/servicos.combos'
import { Route as ServicosAvulsosRouteImport } from './routes/servicos.avulsos'
import { Route as ServicosServiceIdRouteImport } from './routes/servicos.$serviceId'
import { Route as PropostaLeadIdRouteImport } from './routes/proposta.$leadId'
import { Route as PropostaSiteProposalIdRouteImport } from './routes/proposta-site.$proposalId'
import { Route as ModelosDeSitesModelIdRouteImport } from './routes/modelos-de-sites.$modelId'
import { Route as InsightsIdRouteImport } from './routes/insights.$id'
import { Route as DevJobsRouteImport } from './routes/dev.jobs'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AjustesIntegracoesRouteImport } from './routes/ajustes.integracoes'
import { Route as AgendaSetupRouteImport } from './routes/agenda/setup'
import { Route as AgendaOpsRouteImport } from './routes/agenda/ops'
import { Route as AgendaHealthRouteImport } from './routes/agenda/health'
import { Route as AgendaDebugRouteImport } from './routes/agenda/debug'
import { Route as AgendaAjustesRouteImport } from './routes/agenda/ajustes'
import { Route as ServicosDetalhesServiceIdRouteImport } from './routes/servicos.detalhes.$serviceId'
import { Route as ApiPublicMakeCallbackRouteImport } from './routes/api/public/make-callback'

const ProspectingRoute = ProspectingRouteImport.update({
  id: '/prospecting',
  path: '/prospecting',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosDeSitesRoute = ModelosDeSitesRouteImport.update({
  id: '/modelos-de-sites',
  path: '/modelos-de-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IaVendasRoute = IaVendasRouteImport.update({
  id: '/ia-vendas',
  path: '/ia-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupRoute = FollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => rootRouteImport,
} as any)
const DueDiligenceRoute = DueDiligenceRouteImport.update({
  id: '/due-diligence',
  path: '/due-diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscadorRoute = BuscadorRouteImport.update({
  id: '/buscador',
  path: '/buscador',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosDeSitesIndexRoute = ModelosDeSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelosDeSitesRoute,
} as any)
const ServicosOfertasRoute = ServicosOfertasRouteImport.update({
  id: '/servicos/ofertas',
  path: '/servicos/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosNovosRoute = ServicosNovosRouteImport.update({
  id: '/servicos/novos',
  path: '/servicos/novos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIaRoute = ServicosIaRouteImport.update({
  id: '/servicos/ia',
  path: '/servicos/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosDocumentacaoRoute = ServicosDocumentacaoRouteImport.update({
  id: '/servicos/documentacao',
  path: '/servicos/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosCombosRoute = ServicosCombosRouteImport.update({
  id: '/servicos/combos',
  path: '/servicos/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosAvulsosRoute = ServicosAvulsosRouteImport.update({
  id: '/servicos/avulsos',
  path: '/servicos/avulsos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosServiceIdRoute = ServicosServiceIdRouteImport.update({
  id: '/servicos/$serviceId',
  path: '/servicos/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaLeadIdRoute = PropostaLeadIdRouteImport.update({
  id: '/proposta/$leadId',
  path: '/proposta/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaSiteProposalIdRoute = PropostaSiteProposalIdRouteImport.update({
  id: '/proposta-site/$proposalId',
  path: '/proposta-site/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosDeSitesModelIdRoute = ModelosDeSitesModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => ModelosDeSitesRoute,
} as any)
const InsightsIdRoute = InsightsIdRouteImport.update({
  id: '/insights/$id',
  path: '/insights/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevJobsRoute = DevJobsRouteImport.update({
  id: '/dev/jobs',
  path: '/dev/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesIntegracoesRoute = AjustesIntegracoesRouteImport.update({
  id: '/ajustes/integracoes',
  path: '/ajustes/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSetupRoute = AgendaSetupRouteImport.update({
  id: '/agenda/setup',
  path: '/agenda/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaOpsRoute = AgendaOpsRouteImport.update({
  id: '/agenda/ops',
  path: '/agenda/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaHealthRoute = AgendaHealthRouteImport.update({
  id: '/agenda/health',
  path: '/agenda/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaDebugRoute = AgendaDebugRouteImport.update({
  id: '/agenda/debug',
  path: '/agenda/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaAjustesRoute = AgendaAjustesRouteImport.update({
  id: '/agenda/ajustes',
  path: '/agenda/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosDetalhesServiceIdRoute =
  ServicosDetalhesServiceIdRouteImport.update({
    id: '/servicos/detalhes/$serviceId',
    path: '/servicos/detalhes/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMakeCallbackRoute = ApiPublicMakeCallbackRouteImport.update({
  id: '/api/public/make-callback',
  path: '/api/public/make-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/buscador': typeof BuscadorRoute
  '/compare': typeof CompareRoute
  '/crm': typeof CrmRoute
  '/due-diligence': typeof DueDiligenceRoute
  '/followup': typeof FollowupRoute
  '/followups': typeof FollowupsRoute
  '/history': typeof HistoryRoute
  '/ia-vendas': typeof IaVendasRoute
  '/login': typeof LoginRoute
  '/modelos-de-sites': typeof ModelosDeSitesRouteWithChildren
  '/prospecting': typeof ProspectingRoute
  '/agenda/ajustes': typeof AgendaAjustesRoute
  '/agenda/debug': typeof AgendaDebugRoute
  '/agenda/health': typeof AgendaHealthRoute
  '/agenda/ops': typeof AgendaOpsRoute
  '/agenda/setup': typeof AgendaSetupRoute
  '/ajustes/integracoes': typeof AjustesIntegracoesRoute
  '/api/chat': typeof ApiChatRoute
  '/dev/jobs': typeof DevJobsRoute
  '/insights/$id': typeof InsightsIdRoute
  '/modelos-de-sites/$modelId': typeof ModelosDeSitesModelIdRoute
  '/proposta-site/$proposalId': typeof PropostaSiteProposalIdRoute
  '/proposta/$leadId': typeof PropostaLeadIdRoute
  '/servicos/$serviceId': typeof ServicosServiceIdRoute
  '/servicos/avulsos': typeof ServicosAvulsosRoute
  '/servicos/combos': typeof ServicosCombosRoute
  '/servicos/documentacao': typeof ServicosDocumentacaoRoute
  '/servicos/ia': typeof ServicosIaRoute
  '/servicos/novos': typeof ServicosNovosRoute
  '/servicos/ofertas': typeof ServicosOfertasRoute
  '/modelos-de-sites/': typeof ModelosDeSitesIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/api/public/make-callback': typeof ApiPublicMakeCallbackRoute
  '/servicos/detalhes/$serviceId': typeof ServicosDetalhesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/buscador': typeof BuscadorRoute
  '/compare': typeof CompareRoute
  '/crm': typeof CrmRoute
  '/due-diligence': typeof DueDiligenceRoute
  '/followup': typeof FollowupRoute
  '/followups': typeof FollowupsRoute
  '/history': typeof HistoryRoute
  '/ia-vendas': typeof IaVendasRoute
  '/login': typeof LoginRoute
  '/prospecting': typeof ProspectingRoute
  '/agenda/ajustes': typeof AgendaAjustesRoute
  '/agenda/debug': typeof AgendaDebugRoute
  '/agenda/health': typeof AgendaHealthRoute
  '/agenda/ops': typeof AgendaOpsRoute
  '/agenda/setup': typeof AgendaSetupRoute
  '/ajustes/integracoes': typeof AjustesIntegracoesRoute
  '/api/chat': typeof ApiChatRoute
  '/dev/jobs': typeof DevJobsRoute
  '/insights/$id': typeof InsightsIdRoute
  '/modelos-de-sites/$modelId': typeof ModelosDeSitesModelIdRoute
  '/proposta-site/$proposalId': typeof PropostaSiteProposalIdRoute
  '/proposta/$leadId': typeof PropostaLeadIdRoute
  '/servicos/$serviceId': typeof ServicosServiceIdRoute
  '/servicos/avulsos': typeof ServicosAvulsosRoute
  '/servicos/combos': typeof ServicosCombosRoute
  '/servicos/documentacao': typeof ServicosDocumentacaoRoute
  '/servicos/ia': typeof ServicosIaRoute
  '/servicos/novos': typeof ServicosNovosRoute
  '/servicos/ofertas': typeof ServicosOfertasRoute
  '/modelos-de-sites': typeof ModelosDeSitesIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/api/public/make-callback': typeof ApiPublicMakeCallbackRoute
  '/servicos/detalhes/$serviceId': typeof ServicosDetalhesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/buscador': typeof BuscadorRoute
  '/compare': typeof CompareRoute
  '/crm': typeof CrmRoute
  '/due-diligence': typeof DueDiligenceRoute
  '/followup': typeof FollowupRoute
  '/followups': typeof FollowupsRoute
  '/history': typeof HistoryRoute
  '/ia-vendas': typeof IaVendasRoute
  '/login': typeof LoginRoute
  '/modelos-de-sites': typeof ModelosDeSitesRouteWithChildren
  '/prospecting': typeof ProspectingRoute
  '/agenda/ajustes': typeof AgendaAjustesRoute
  '/agenda/debug': typeof AgendaDebugRoute
  '/agenda/health': typeof AgendaHealthRoute
  '/agenda/ops': typeof AgendaOpsRoute
  '/agenda/setup': typeof AgendaSetupRoute
  '/ajustes/integracoes': typeof AjustesIntegracoesRoute
  '/api/chat': typeof ApiChatRoute
  '/dev/jobs': typeof DevJobsRoute
  '/insights/$id': typeof InsightsIdRoute
  '/modelos-de-sites/$modelId': typeof ModelosDeSitesModelIdRoute
  '/proposta-site/$proposalId': typeof PropostaSiteProposalIdRoute
  '/proposta/$leadId': typeof PropostaLeadIdRoute
  '/servicos/$serviceId': typeof ServicosServiceIdRoute
  '/servicos/avulsos': typeof ServicosAvulsosRoute
  '/servicos/combos': typeof ServicosCombosRoute
  '/servicos/documentacao': typeof ServicosDocumentacaoRoute
  '/servicos/ia': typeof ServicosIaRoute
  '/servicos/novos': typeof ServicosNovosRoute
  '/servicos/ofertas': typeof ServicosOfertasRoute
  '/modelos-de-sites/': typeof ModelosDeSitesIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/api/public/make-callback': typeof ApiPublicMakeCallbackRoute
  '/servicos/detalhes/$serviceId': typeof ServicosDetalhesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/buscador'
    | '/compare'
    | '/crm'
    | '/due-diligence'
    | '/followup'
    | '/followups'
    | '/history'
    | '/ia-vendas'
    | '/login'
    | '/modelos-de-sites'
    | '/prospecting'
    | '/agenda/ajustes'
    | '/agenda/debug'
    | '/agenda/health'
    | '/agenda/ops'
    | '/agenda/setup'
    | '/ajustes/integracoes'
    | '/api/chat'
    | '/dev/jobs'
    | '/insights/$id'
    | '/modelos-de-sites/$modelId'
    | '/proposta-site/$proposalId'
    | '/proposta/$leadId'
    | '/servicos/$serviceId'
    | '/servicos/avulsos'
    | '/servicos/combos'
    | '/servicos/documentacao'
    | '/servicos/ia'
    | '/servicos/novos'
    | '/servicos/ofertas'
    | '/modelos-de-sites/'
    | '/servicos/'
    | '/api/public/make-callback'
    | '/servicos/detalhes/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/buscador'
    | '/compare'
    | '/crm'
    | '/due-diligence'
    | '/followup'
    | '/followups'
    | '/history'
    | '/ia-vendas'
    | '/login'
    | '/prospecting'
    | '/agenda/ajustes'
    | '/agenda/debug'
    | '/agenda/health'
    | '/agenda/ops'
    | '/agenda/setup'
    | '/ajustes/integracoes'
    | '/api/chat'
    | '/dev/jobs'
    | '/insights/$id'
    | '/modelos-de-sites/$modelId'
    | '/proposta-site/$proposalId'
    | '/proposta/$leadId'
    | '/servicos/$serviceId'
    | '/servicos/avulsos'
    | '/servicos/combos'
    | '/servicos/documentacao'
    | '/servicos/ia'
    | '/servicos/novos'
    | '/servicos/ofertas'
    | '/modelos-de-sites'
    | '/servicos'
    | '/api/public/make-callback'
    | '/servicos/detalhes/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/buscador'
    | '/compare'
    | '/crm'
    | '/due-diligence'
    | '/followup'
    | '/followups'
    | '/history'
    | '/ia-vendas'
    | '/login'
    | '/modelos-de-sites'
    | '/prospecting'
    | '/agenda/ajustes'
    | '/agenda/debug'
    | '/agenda/health'
    | '/agenda/ops'
    | '/agenda/setup'
    | '/ajustes/integracoes'
    | '/api/chat'
    | '/dev/jobs'
    | '/insights/$id'
    | '/modelos-de-sites/$modelId'
    | '/proposta-site/$proposalId'
    | '/proposta/$leadId'
    | '/servicos/$serviceId'
    | '/servicos/avulsos'
    | '/servicos/combos'
    | '/servicos/documentacao'
    | '/servicos/ia'
    | '/servicos/novos'
    | '/servicos/ofertas'
    | '/modelos-de-sites/'
    | '/servicos/'
    | '/api/public/make-callback'
    | '/servicos/detalhes/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  BuscadorRoute: typeof BuscadorRoute
  CompareRoute: typeof CompareRoute
  CrmRoute: typeof CrmRoute
  DueDiligenceRoute: typeof DueDiligenceRoute
  FollowupRoute: typeof FollowupRoute
  FollowupsRoute: typeof FollowupsRoute
  HistoryRoute: typeof HistoryRoute
  IaVendasRoute: typeof IaVendasRoute
  LoginRoute: typeof LoginRoute
  ModelosDeSitesRoute: typeof ModelosDeSitesRouteWithChildren
  ProspectingRoute: typeof ProspectingRoute
  AgendaAjustesRoute: typeof AgendaAjustesRoute
  AgendaDebugRoute: typeof AgendaDebugRoute
  AgendaHealthRoute: typeof AgendaHealthRoute
  AgendaOpsRoute: typeof AgendaOpsRoute
  AgendaSetupRoute: typeof AgendaSetupRoute
  AjustesIntegracoesRoute: typeof AjustesIntegracoesRoute
  ApiChatRoute: typeof ApiChatRoute
  DevJobsRoute: typeof DevJobsRoute
  InsightsIdRoute: typeof InsightsIdRoute
  PropostaSiteProposalIdRoute: typeof PropostaSiteProposalIdRoute
  PropostaLeadIdRoute: typeof PropostaLeadIdRoute
  ServicosServiceIdRoute: typeof ServicosServiceIdRoute
  ServicosAvulsosRoute: typeof ServicosAvulsosRoute
  ServicosCombosRoute: typeof ServicosCombosRoute
  ServicosDocumentacaoRoute: typeof ServicosDocumentacaoRoute
  ServicosIaRoute: typeof ServicosIaRoute
  ServicosNovosRoute: typeof ServicosNovosRoute
  ServicosOfertasRoute: typeof ServicosOfertasRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
  ApiPublicMakeCallbackRoute: typeof ApiPublicMakeCallbackRoute
  ServicosDetalhesServiceIdRoute: typeof ServicosDetalhesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prospecting': {
      id: '/prospecting'
      path: '/prospecting'
      fullPath: '/prospecting'
      preLoaderRoute: typeof ProspectingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos-de-sites': {
      id: '/modelos-de-sites'
      path: '/modelos-de-sites'
      fullPath: '/modelos-de-sites'
      preLoaderRoute: typeof ModelosDeSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-vendas': {
      id: '/ia-vendas'
      path: '/ia-vendas'
      fullPath: '/ia-vendas'
      preLoaderRoute: typeof IaVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followup': {
      id: '/followup'
      path: '/followup'
      fullPath: '/followup'
      preLoaderRoute: typeof FollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/due-diligence': {
      id: '/due-diligence'
      path: '/due-diligence'
      fullPath: '/due-diligence'
      preLoaderRoute: typeof DueDiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscador': {
      id: '/buscador'
      path: '/buscador'
      fullPath: '/buscador'
      preLoaderRoute: typeof BuscadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos-de-sites/': {
      id: '/modelos-de-sites/'
      path: '/'
      fullPath: '/modelos-de-sites/'
      preLoaderRoute: typeof ModelosDeSitesIndexRouteImport
      parentRoute: typeof ModelosDeSitesRoute
    }
    '/servicos/ofertas': {
      id: '/servicos/ofertas'
      path: '/servicos/ofertas'
      fullPath: '/servicos/ofertas'
      preLoaderRoute: typeof ServicosOfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/novos': {
      id: '/servicos/novos'
      path: '/servicos/novos'
      fullPath: '/servicos/novos'
      preLoaderRoute: typeof ServicosNovosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/ia': {
      id: '/servicos/ia'
      path: '/servicos/ia'
      fullPath: '/servicos/ia'
      preLoaderRoute: typeof ServicosIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/documentacao': {
      id: '/servicos/documentacao'
      path: '/servicos/documentacao'
      fullPath: '/servicos/documentacao'
      preLoaderRoute: typeof ServicosDocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/combos': {
      id: '/servicos/combos'
      path: '/servicos/combos'
      fullPath: '/servicos/combos'
      preLoaderRoute: typeof ServicosCombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/avulsos': {
      id: '/servicos/avulsos'
      path: '/servicos/avulsos'
      fullPath: '/servicos/avulsos'
      preLoaderRoute: typeof ServicosAvulsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$serviceId': {
      id: '/servicos/$serviceId'
      path: '/servicos/$serviceId'
      fullPath: '/servicos/$serviceId'
      preLoaderRoute: typeof ServicosServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta/$leadId': {
      id: '/proposta/$leadId'
      path: '/proposta/$leadId'
      fullPath: '/proposta/$leadId'
      preLoaderRoute: typeof PropostaLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta-site/$proposalId': {
      id: '/proposta-site/$proposalId'
      path: '/proposta-site/$proposalId'
      fullPath: '/proposta-site/$proposalId'
      preLoaderRoute: typeof PropostaSiteProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos-de-sites/$modelId': {
      id: '/modelos-de-sites/$modelId'
      path: '/$modelId'
      fullPath: '/modelos-de-sites/$modelId'
      preLoaderRoute: typeof ModelosDeSitesModelIdRouteImport
      parentRoute: typeof ModelosDeSitesRoute
    }
    '/insights/$id': {
      id: '/insights/$id'
      path: '/insights/$id'
      fullPath: '/insights/$id'
      preLoaderRoute: typeof InsightsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/jobs': {
      id: '/dev/jobs'
      path: '/dev/jobs'
      fullPath: '/dev/jobs'
      preLoaderRoute: typeof DevJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes/integracoes': {
      id: '/ajustes/integracoes'
      path: '/ajustes/integracoes'
      fullPath: '/ajustes/integracoes'
      preLoaderRoute: typeof AjustesIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/setup': {
      id: '/agenda/setup'
      path: '/agenda/setup'
      fullPath: '/agenda/setup'
      preLoaderRoute: typeof AgendaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/ops': {
      id: '/agenda/ops'
      path: '/agenda/ops'
      fullPath: '/agenda/ops'
      preLoaderRoute: typeof AgendaOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/health': {
      id: '/agenda/health'
      path: '/agenda/health'
      fullPath: '/agenda/health'
      preLoaderRoute: typeof AgendaHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/debug': {
      id: '/agenda/debug'
      path: '/agenda/debug'
      fullPath: '/agenda/debug'
      preLoaderRoute: typeof AgendaDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/ajustes': {
      id: '/agenda/ajustes'
      path: '/agenda/ajustes'
      fullPath: '/agenda/ajustes'
      preLoaderRoute: typeof AgendaAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/detalhes/$serviceId': {
      id: '/servicos/detalhes/$serviceId'
      path: '/servicos/detalhes/$serviceId'
      fullPath: '/servicos/detalhes/$serviceId'
      preLoaderRoute: typeof ServicosDetalhesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/make-callback': {
      id: '/api/public/make-callback'
      path: '/api/public/make-callback'
      fullPath: '/api/public/make-callback'
      preLoaderRoute: typeof ApiPublicMakeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ModelosDeSitesRouteChildren {
  ModelosDeSitesModelIdRoute: typeof ModelosDeSitesModelIdRoute
  ModelosDeSitesIndexRoute: typeof ModelosDeSitesIndexRoute
}

const ModelosDeSitesRouteChildren: ModelosDeSitesRouteChildren = {
  ModelosDeSitesModelIdRoute: ModelosDeSitesModelIdRoute,
  ModelosDeSitesIndexRoute: ModelosDeSitesIndexRoute,
}

const ModelosDeSitesRouteWithChildren = ModelosDeSitesRoute._addFileChildren(
  ModelosDeSitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  BuscadorRoute: BuscadorRoute,
  CompareRoute: CompareRoute,
  CrmRoute: CrmRoute,
  DueDiligenceRoute: DueDiligenceRoute,
  FollowupRoute: FollowupRoute,
  FollowupsRoute: FollowupsRoute,
  HistoryRoute: HistoryRoute,
  IaVendasRoute: IaVendasRoute,
  LoginRoute: LoginRoute,
  ModelosDeSitesRoute: ModelosDeSitesRouteWithChildren,
  ProspectingRoute: ProspectingRoute,
  AgendaAjustesRoute: AgendaAjustesRoute,
  AgendaDebugRoute: AgendaDebugRoute,
  AgendaHealthRoute: AgendaHealthRoute,
  AgendaOpsRoute: AgendaOpsRoute,
  AgendaSetupRoute: AgendaSetupRoute,
  AjustesIntegracoesRoute: AjustesIntegracoesRoute,
  ApiChatRoute: ApiChatRoute,
  DevJobsRoute: DevJobsRoute,
  InsightsIdRoute: InsightsIdRoute,
  PropostaSiteProposalIdRoute: PropostaSiteProposalIdRoute,
  PropostaLeadIdRoute: PropostaLeadIdRoute,
  ServicosServiceIdRoute: ServicosServiceIdRoute,
  ServicosAvulsosRoute: ServicosAvulsosRoute,
  ServicosCombosRoute: ServicosCombosRoute,
  ServicosDocumentacaoRoute: ServicosDocumentacaoRoute,
  ServicosIaRoute: ServicosIaRoute,
  ServicosNovosRoute: ServicosNovosRoute,
  ServicosOfertasRoute: ServicosOfertasRoute,
  ServicosIndexRoute: ServicosIndexRoute,
  ApiPublicMakeCallbackRoute: ApiPublicMakeCallbackRoute,
  ServicosDetalhesServiceIdRoute: ServicosDetalhesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
